apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  containers:
  - name: main-app
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
  - name: log-sidecar
    image: busybox
    restartPolicy: Always
    command: ["sh", "-c", "while true; do echo sidecar running $(date); sleep 10; done"]